### ISSUE TITLE
朴素贝叶斯分类器中的问题

### ISSUE THREAD

**Issue by MoidzzZ** [sun-roc/Machine_Learning_in_Action#1]
正如你在注释中提到的一样，使用split将文章分成了86份。
而你在接下来的循环中，条件使用的是`for i in range(85):`，这导致对文章的计数出现了问题，你可以尝试打印查看一下结果。
将其改为`for i in range(1, 86):`后应该是正常情况。

**Comment by MoidzzZ** [comment]
> 

以及统计的词频应该不是每一篇文章，而是所有的文章合起来。
此外，在计算文章的频率用来MAP fi的时候，分母应该为训练集的合，你还算上了测试集。

**Comment by sun-roc** [comment]
> 正如你在注释中提到的一样，使用split将文章分成了86份。 而你在接下来的循环中，条件使用的是`for i in range(85):`，这导致对文章的计数出现了问题，你可以尝试打印查看一下结果。 将其改为`for i in range(1, 86):`后应该是正常情况。

这部分应该没问题吧，数组index最大就是[85]，[0]是空白不影响。最后输出的结果编号也是未知文章的编号

**Comment by sun-roc** [comment]
> > 
> 
> 以及统计的词频应该不是每一篇文章，而是所有的文章合起来。 此外，在计算文章的频率用来MAP fi的时候，分母应该为训练集的合，你还算上了测试集。

这个每太看懂是什么意思。贝叶斯公式中所有文章中词频P(X)都在分母应该不用计算，只要计算每类文章的词频就好吧。

**Comment by MoidzzZ** [comment]
> > 正如你在注释中提到的一样，使用split将文章分成了86份。 而你在接下来的循环中，条件使用的是`for i in range(85):`，这导致对文章的计数出现了问题，你可以尝试打印查看一下结果。 将其改为`for i in range(1, 86):`后应该是正常情况。
> 
> 这部分应该没问题吧，数组index最大就是[85]，[0]是空白不影响。最后输出的结果编号也是未知文章的编号

很高兴你现在在线，range(85)生成的是0到84的序列，而文章列表的长度为86，因为最后一篇文章不是未知文章所以没有影响到，但影响了最后一篇文章所属类别的分布。

**Comment by MoidzzZ** [comment]
> > > 
> > 
> > 
> > 以及统计的词频应该不是每一篇文章，而是所有的文章合起来。 此外，在计算文章的频率用来MAP fi的时候，分母应该为训练集的合，你还算上了测试集。
> 
> 这个每太看懂是什么意思。贝叶斯公式中所有文章中词频P(X)都在分母应该不用计算，只要计算每类文章的词频就好吧。

我这句话针对的是你的备注，#统计每篇文章的出现次数超过10词的高频词,组成一个词向量，应该是所有文章中出现次数，抱歉没有注意引用。

**Comment by sun-roc** [comment]
> > > 正如你在注释中提到的一样，使用split将文章分成了86份。 而你在接下来的循环中，条件使用的是`for i in range(85):`，这导致对文章的计数出现了问题，你可以尝试打印查看一下结果。 将其改为`for i in range(1, 86):`后应该是正常情况。
> > 
> > 
> > 这部分应该没问题吧，数组index最大就是[85]，[0]是空白不影响。最后输出的结果编号也是未知文章的编号
> 
> 很高兴你现在在线，range(85)生成的是0到84的序列，而文章列表的长度为86，因为最后一篇文章不是未知文章所以没有影响到，但影响了最后一篇文章所属类别的分布。

你说的对，是我没注意。

**Comment by sun-roc** [comment]
> > > > 
> > > 
> > > 
> > > 以及统计的词频应该不是每一篇文章，而是所有的文章合起来。 此外，在计算文章的频率用来MAP fi的时候，分母应该为训练集的合，你还算上了测试集。
> > 
> > 
> > 这个每太看懂是什么意思。贝叶斯公式中所有文章中词频P(X)都在分母应该不用计算，只要计算每类文章的词频就好吧。
> 
> 我这句话针对的是你的备注，#统计每篇文章的出现次数超过10词的高频词,组成一个词向量，应该是所有文章中出现次数，抱歉没有注意引用。

是的，代码中输出的结果确实是所有文章中超过10次的单词，这里是我注释有问题。

**Comment by MoidzzZ** [comment]
非常感谢你的分享，说实话刚看到这个任务没提取数据特征的头绪。

**Comment by sun-roc** [comment]
崇新的同学吗(っ•̀ω•́)っ✎⁾⁾

**Comment by MoidzzZ** [comment]
> 崇新的同学吗(っ•̀ω•́)っ✎⁾⁾

不妙，好像copy被发现了（：
是哪一位学长啊，按年份是18级的？

**Comment by sun-roc** [comment]
> > 崇新的同学吗(っ•̀ω•́)っ✎⁾⁾
> 
> 不妙，好像copy被发现了（： 是哪一位学长啊，按年份是18级的？

哈哈哈，大家都这么过来的
